### ISSUE TITLE
File path is wrong format

### ISSUE THREAD

**Issue by carlucci001** [akeeba/nativexplatform#11] opened 2017-11-01 18:26 UTC
I receive an error that the path is the wrong format. I am using the tools latest version on windows 10. I tried running repair and it installed the .net framework. I ran again and it failed again about half way through. Please advise.

**Comment by nikosdion** [comment] 2017-11-02 13:01
User error. Also duplicate of gh-2.

**Closed by nikosdion** 2017-11-02 13:01 UTC
